# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"\x06\n\x04Null\" \n\x04TeId\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\n\n\x02id\x18\x02 \x01(\x03\"\x15\n\x03Per\x12\x0e\n\x06period\x18\x01 \x01(\x03\"&\n\x05\x43heck\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\"<\n\x06Leader\x12\x0f\n\x02id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x11\n\x04\x61\x64\x64r\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x07\n\x05_addr2y\n\x04Raft\x12\x1c\n\x0bRequestVote\x12\x05.TeId\x1a\x06.Check\x12\x1e\n\rAppendEntries\x12\x05.TeId\x1a\x06.Check\x12\x1b\n\tGetLeader\x12\x05.Null\x1a\x07.Leader\x12\x16\n\x07Suspend\x12\x04.Per\x1a\x05.Nullb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NULL._serialized_start=14
  _NULL._serialized_end=20
  _TEID._serialized_start=22
  _TEID._serialized_end=54
  _PER._serialized_start=56
  _PER._serialized_end=77
  _CHECK._serialized_start=79
  _CHECK._serialized_end=117
  _LEADER._serialized_start=119
  _LEADER._serialized_end=179
  _RAFT._serialized_start=181
  _RAFT._serialized_end=302
# @@protoc_insertion_point(module_scope)
